hash:
  memory: 65536
  time: 1
  threads: 2
  key_len: 32
  salt_length: 16

http:
  addr: "0.0.0.0:8000"
  cors_url:
  - "http://127.0.0.1:7000"
  - "http://localhost:7000"
  idle_timeout: "60s"
  read_timeout: "20s"
  write_timeout: "30s"

jwt:
  access_ttl: "30m"
  refresh_ttl: "168h"

database:
  host: "127.0.0.1"
  port: 5432
  name: "go_todo_db"
  max_idle_conns: 100
  max_open_conns: 100
  max_conn_lifetime: "1h"
  conn_timeout: "30s"

